version: '3'

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    networks:
      - web
    user: "1000"
    ports:
      - 3100:3000
    volumes:
      - /home/user/Services/Monitoring/grafana:/config
    environment:
      - GF_PATHS_DATA=/config/data
      - GF_PATHS_LOGS=/config/logs
      - GF_PATHS_PLUGINS=/config/plugins
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-worldmap-panel
    depends_on:
      - influxdb
      - varken
    labels:
      - "traefik.enable=true"
      - "traefik.backend=grafana"
      - "traefik.frontend.rule=Host:grafana.domain.com"
      - "traefik.docker.network=web"
      - "traefik.port=3000"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=domain.com"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.customFrameOptionsValue=allow-from https:domain.com"
      - "traefik.frontend.headers.referrerPolicy=strict-origin"
      - "traefik.frontend.headers.contentSecurityPolicy=default-src https: 'unsafe-inline' 'unsafe-eval'"
    restart: unless-stopped

  influxdb:
    image: influxdb
    container_name: influxdb
    hostname: influxdb
    networks:
      - web
    ports:
      - 8086:8086
    volumes:
      - /home/user/Services/Monitoring/influxdb:/var/lib/influxdb
      - /home/user/Services/Monitoring/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
    restart: unless-stopped

  varken:
    hostname: varken
    container_name: varken
    image: boerderij/varken
    # user: "1000"
    networks:
      - web
    volumes:
      - /home/user/Services/Monitoring/varken:/config
    environment:
      - TZ=Indian/Mauritius
    depends_on:
      - influxdb
    restart: unless-stopped

  speedtest:
    image: atribe/speedtest-for-influxdb-and-grafana
    container_name: speedtest
    hostname: speedtest
    networks:
      - web
    volumes:
      - /home/user/Services/Monitoring/speedtest/config.ini:/src/config.ini
    depends_on:
      - influxdb
    restart: unless-stopped

networks:
  web:
    external: true
